### ISSUE TITLE
Sidebar and Leaflet 1.1.0 

### ISSUE THREAD

**Issue by mykolakozyr** [tdukr/otg#5]
https://github.com/Turbo87/leaflet-sidebar/issues/49

**Comment by mykolakozyr** [comment]
try with $ajax

**Comment by mykolakozyr** [comment]
Added not existing function to the openSidebar and It started to work. I'm closing the issue here, but it still has to be fixed

**Comment by encleadus** [comment]
Hi, Could you share your code, please? We are experiencing the same error with leaflet sidebar.
